SRC = unity/unity.c\
src/Addition.c\
src/Multiplication.c\
src/Subtraction.c\
src/Division.c\
src/Modulus.c\
src/Power.c\
src/Factorial.c\
test/test_calculator.c\


INC = -Iunity\
-Iinc\
-Itest

#To check if the OS is Windows or Linux and set the executable file extension and delete command accordingly
ifdef OS
   RM = del /q
   FixPath = $(subst /,\,$1)
   EXEC = exe
else
   ifeq ($(shell uname), Linux)
      RM = rm -rf
      FixPath = $1
	  EXEC = out
   endif
endif

PROJECT_NAME = calculator.exe

$(PROJECT_NAME): $(SRC)
	gcc $(SRC) $(INC) -o $(PROJECT_NAME)

run:$(PROJECT_NAME)
	$(PROJECT_NAME)



